site_name: Robotprogramozás ROS környezetben
site_url: https://example.com/
site_description: Robotprogramozás ROS környezetben
site_author: Nagy Tamás

nav:
    - Kezdőlap: index.md
    - Tananyagok: 
        - 1. Bevezetés: 01_intro.md
        - 2. Linux, ROS alapismeretek: 02_linux_ros_principles.md
        - 3. Python alapismeretek,  ROS kommunikáció gyakorlása: 03_python_principles.md
        - 4. Verziókövetés, Git: 04_git.md
        - 5. Robotikai alapismeretek, Sebészrobot programozása: 05_da_vinci.md
        - 8. Roslaunch, saját üzenetek, action, service: 08_roslaunch.md
        - 12. Kinematika, inverz kinematika: 12_robotics_principles.md
    - Kötelező program: kotprog.md
    

theme:
    name: material
    palette:
        scheme: default
        primary: blue grey
    language: hu
    features:
        - navigation.tabs
        - toc.integrate
        
        

extra:                                              
  alternate:  
    - name: English
      link: https://abc-irobotics.github.io/ros_course_materials_en/
      lang: en

    - name: Hungarian
      link: https://abc-irobotics.github.io/ros_course_materials_hu/
      lang: hu
   
plugins:
    - search
    - pdf-export
       
      
markdown_extensions:
    - pymdownx.arithmatex:
        generic: true 
    - mkdocs_graphviz
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - tables

    
copyright: Copyright &copy; 2022 <a href="mailto:tamas.daniel.nagy@irob.uni-obuda.hu">Tamas D. Nagy</a>.


extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js
    

